### PR TITLE
Feature/tailwind update

### PR DESCRIPTION
**Pull request by willans**

### CODE REVIEW

**Comment by gilleard** [comment]
Noticed there's manifest file changes as part of this - shouldn't we be ignoring that file?

**Comment by willans** [comment]
Yes. But a change @wilkinsocks did way back when resulted in this file being checked in. Not sure how to remove it.

**Comment by gilleard** [comment]
Removed it now, but Matt might argue it's there so backend works without having to compiled the FE.

I think the laravel mix helper shouldn't throw exceptions on dev for missing files tbh.

**Comment by willans** [comment]
Do we need to do anything else on this?

**Comment by wilkinsocks** [comment]
Fine with me — I agree with Gilly on the manifest exception, seems a bit OTT.

**Comment by wilkinsocks** [comment]
Might need to watch what the yarn.lock does here — potentially merge master in and rebuild based on what I said in Slack?

**Pull request merged**
