### PR TITLE
Updates naming of home view

### PR DESCRIPTION
**Pull request by willans**
We use a standard index and view naming convention, where index is a listing page, and view is a single page.

home/home makes little sense.

### CODE REVIEW

**Comment by wilkinsocks** [comment]
Thanks @willans! yeah we've been meaning to sort this for a while! 😅 

I've just pushed something in too, to update the controller/backend to remove that invoke stuff which was equally jarring around the **Home** domain.

Just a few comments from me:

I wonder if semantically should the homepage be `index` over a detail page? especially with it being on `/` — thinking about the wider context of the site, and additionally web-servers serving an index file for `/`

I guess really, standalone pages are an index, even though it **might not** have distinct children? but equally, in some edge scenarios it could be ok to break out of a naming convention. e.g. I think you could have `pages/privacy` as it could be trivial to create `privacy/index` for the sake of a convention — since that directly correlates to the app directory structure, over time this could unintentionally create a maze-like developer experience.

Also on a side-note, not sure about the index/view naming convention as a statement. It should really be `index` and `detail`? _(We've previously [discussed this](https://engageinteractive.slack.com/archives/GH8HGLNJX/p1570530386005900))_

Since everything is a view, the **'view'** in the wider context is the entire UI, so I don't think we should be muddying the waters with a dual meaning. (_Further reading: [MVVM software architectural pattern](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel)_)

I feel firm on the word **index**, and I don't think we should use be using the word **view** to refer to singular models, but I'm not fussy about the naming of **detail** though, if someone has an alternative name? (I can't think of anything better though).

**Comment by willans** [comment]
I feel that the folder structure is too nested, and that's part of the problem. For pages that have no children, particularly the homepage - it shouldn't be in a folder at all.

For example, this is a file and folder structure (as on Taylors OOH) is a lot cleaner:
contact.blade.php
copy.blade.php
distributors.blade.php
home.blade.php
team.blade.php
news (folder)
news/index.blade.php
news/detail.blade.php

**Comment by wilkinsocks** [comment]
To be honest, I agree.

I think especially smaller apps maybe it's ok to simplify like this, and certainly in the context of the homepage, that could have it's own named blade in the app root?

**Comment by wilkinsocks** [comment]
Just pushed an update based on the discussion here.

I've moved `/home/view` to become `/homepage`

**Review by wilkinsocks — APPROVED** [review]

**Pull request merged**
